language: node_js
node_js:
  - 14

stages:
  - lint
  - build

services:
  - docker

before_install:
  - npm install eslint

jobs:
  include:
    - stage: lint
      script: ./node_modules/.bin/eslint . ./**/*.js
    - stage: build
      script: 
        - docker build -t rcsillag/website-themes .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push rcsillag/website-themes
        