language: node_js
node_js:
  - 14

services:
  - docker

before_install:
  - npm install eslint

jobs:
  include:
    - stage: lint
      script: ./node_modules/.bin/eslint . ./**/*.js
    - stage: build
      script: docker build -t rcsillag/website-themes .